"use client";

import { useEffect, type RefObject } from "react";
import { smoothScrollTo, isScrollAnimating, isAnimationEcho } from "@/lib/smoothScrollTo";

const DESKTOP_QUERY =
  "(min-width: 768px) and (pointer: fine) and (prefers-reduced-motion: no-preference)";
const ADVANCE_RATIO = 0.12;
const VELOCITY_ADVANCE = 0.6; // px/ms (~600px/s) — a firm flick advances a slide
const MIN_MOVE_FOR_VELOCITY = 0.02; // fraction of viewport, guards against noise spikes
const SETTLE_DEBOUNCE = 260; // ms of no scroll activity before deciding — must clear the
// browser's own native "smooth" animation for a single wheel notch, or we'd react mid-flight.

/** Free scrolling during the gesture; once scroll activity pauses for
 *  SETTLE_DEBOUNCE, move to the next or previous panel if the user crossed
 *  ADVANCE_RATIO of the viewport (or flicked fast enough over a shorter
 *  distance), otherwise return to where the gesture started. */
export function useSlideSnap(containerRef: RefObject<HTMLElement | null>) {
  useEffect(() => {
    const container = containerRef.current;
    if (!container || !window.matchMedia(DESKTOP_QUERY).matches) return;

    const panels = container.querySelectorAll(".panel");
    if (panels.length < 2) return;
    const last = panels.length - 1;

    let anchor = Math.round(window.scrollY / window.innerHeight);
    let lastSampleT = 0;
    let lastSampleY = 0;
    let maxVelocity = 0; // signed px/ms, peak over the current gesture
    let timer: number | undefined;

    const settle = () => {
      const h = window.innerHeight;
      const pos = window.scrollY / h;
      const moved = pos - anchor;
      let target = anchor;

      if (Math.abs(moved) > 1.5) {
        target = Math.round(pos);
      } else if (
        moved > ADVANCE_RATIO ||
        (moved > MIN_MOVE_FOR_VELOCITY && maxVelocity > VELOCITY_ADVANCE)
      ) {
        target = anchor + 1;
      } else if (
        moved < -ADVANCE_RATIO ||
        (moved < -MIN_MOVE_FOR_VELOCITY && maxVelocity < -VELOCITY_ADVANCE)
      ) {
        target = anchor - 1;
      }

      target = Math.min(Math.max(target, 0), last);
      anchor = target;
      maxVelocity = 0;
      lastSampleT = 0;
      if (Math.abs(window.scrollY - target * h) > 1) {
        smoothScrollTo(target * h);
      }
    };

    const onScroll = () => {
      const y = window.scrollY;

      // Ignore scroll events generated by our own smoothScrollTo animation —
      // whether still actively stepping, or a late echo the browser is only
      // now delivering after keeping the main thread busy. Otherwise either
      // one looks like a continuing user gesture and corrupts the landing
      // position (see isAnimationEcho for why value-range, not a timeout).
      if (isScrollAnimating() || isAnimationEcho(y)) {
        lastSampleT = 0;
        window.clearTimeout(timer);
        return;
      }

      const now = performance.now();
      if (lastSampleT) {
        const dt = now - lastSampleT;
        if (dt > 0) {
          const v = (y - lastSampleY) / dt;
          if (Math.abs(v) > Math.abs(maxVelocity)) maxVelocity = v;
        }
      }
      lastSampleT = now;
      lastSampleY = y;

      window.clearTimeout(timer);
      timer = window.setTimeout(settle, SETTLE_DEBOUNCE);
    };

    window.addEventListener("scroll", onScroll, { passive: true });
    return () => {
      window.clearTimeout(timer);
      window.removeEventListener("scroll", onScroll);
    };
  }, [containerRef]);
}
